# Site settings
email: 'sunseeker@wmich.edu'
description: 'The Sunseeker Solar Car Project at Western Michigan University is a team of students who design, build, and compete with solar powered vehicles.'
baseurl: '/sunseeker'
url: 'https://www.wmich.edu'

foundation_url: 'https://securelb.imodules.com/s/1428/gid2/index.aspx?sid=1428&amp;gid=2&amp;pgid=418&amp;cid=1173&amp;bledit=1&amp;dids=158'
donation_amounts: ['25', '50', '100', '250', '500', '1000', '2500']

# Build settings
markdown: 'kramdown'

permalink: '/blog/:categories/:year/:month/:day/:title.html'

exclude: ['package.json', 'bower.json', 'README.md', 'node_modules', 'deploy.js', 'Gemfile', 'Gemfile.lock']
include: ['.htsecure', '.htaccess']
